/*
 * text.js — every word shown on the site.
 * These are the defaults for every site. A site changes its own words in its site.json, e.g.
 *   {"siteTitle": "AA No Reset Solo", "siteSubtitle": "(My Log)", "colTime": "Time"}
 */
const T = {
  // Header
  siteTitle: "AA No Reset Solo",
  siteSubtitle: "",
  tabOverview: "Overview",
  tabStats: "Stats",
  tabCompare: "Compare",

  // Overview page
  pb: "PB",
  noPbYet: "The fastest valid run shows here once a run is added.",
  sumOfBest: "Sum of best",
  averageTime: "Average time",
  totalRuns: "Total runs",
  totalPlaytime: "Total playtime",
  fastestSplits: "Fastest Splits",
  averageStats: "Average stats",
  runsTitle: "Runs",
  noRunsYet: "No runs yet.",
  noRunYet: "No run yet",
  averagePrefix: "avg",

  // Runs table column headings
  colRun: "Run",
  colDate: "Date",
  colHundred: "100%",
  colTime: "Time (IGT)",

  // Note shown when hovering the "100%" heading in the runs table (HTML allowed)
  hundredNote: `<b>100%:</b> No = thunderless* (79/80 adv.) unless otherwise stated.<br>*The player is incentivised to prioritise obtaining a Trident enchanted with Channeling, and to not have slept**.<br>**If the player has slept, they must wait at least 10 minutes (min. weather cycle) until they can declare a "thunderless" run.`,

  // "100%" column values
  hundredYes: "Yes",
  hundredNo: "No",
  hundredInvalid: "Invalid",

  // Other splits (shown under the split splits on Overview)
  skullsSplit: "Skulls",

  // Stats page
  runWord: "Run",
  seedLabel: "Seed:",
  timeLabel: "Time (IGT)",
  video: "Video",
  watchVideo: "Watch the video",
  screenshot: "Screenshot",
  openScreenshot: "Open the screenshot",
  noLogTitle: "No log for this run",
  noLogNote: "This run was added without a Hermes log, so there are no graphs or stats, only what's written in runs.json.",
  hundredUnknown: "—",
  goToRun: "Go to run",
  noSuchRun: "No run",
  previousRun: "Previous run",
  nextRun: "Next run",
  invalidRun: "Invalid run.",
  invalidRunMissing: "Missing",
  invalidRunNote: "It's left out of PBs and bests.",
  andMore: n => `and ${n} more`,
  splitsTitle: "Splits",
  progressTitle: "Progress over IGT",
  fullScreen: "Full screen",
  exitFullScreen: "Exit full screen",
  showing: "Showing",
  reset: "Reset",
  keysHelp: `<span>Drag to zoom</span><span><kbd>+</kbd><kbd>−</kbd> zoom</span><span><kbd>←</kbd><kbd>→</kbd> move</span><span><kbd>0</kbd> reset</span><span><kbd>F</kbd> full screen</span><span><kbd>[</kbd><kbd>]</kbd> previous / next run</span>`,
  overworld: "Overworld",
  nether: "Nether",
  theEnd: "The End",
  lineAdvancements: "Advancements",
  runStatsTitle: "Run stats",
  debrisTitle: "Debris",
  skullsTitle: "Skulls",
  rareBiomesTitle: "Rare biomes",
  notesTitle: "Notes",
  noDebris: "No debris session found in this log.",
  noSkulls: "No skulls in this log.",
  incomplete: "incomplete",
  missing: "Missing",
  showRunBar: "Show run bar",
  minimise: "Minimise",

  // Compare page
  cmpAdd: "Pick a run…",
  cmpMine: "Runs on this site",
  cmpUploadedRuns: "Your uploaded runs",
  cmpUploaded: "uploaded",
  cmpUpload: "Upload Hermes log",
  cmpReading: "Reading…",
  cmpBadJson: "This isn't a saved run.",
  cmpSave: "Save as a file",
  cmpForget: "Forget uploaded runs",
  cmpKeysHelp: `<span>Drag to zoom</span><span><kbd>+</kbd><kbd>−</kbd> zoom</span><span><kbd>←</kbd><kbd>→</kbd> move</span><span><kbd>0</kbd> reset</span><span><kbd>F</kbd> full screen</span>`,
  cmpSegment: "This split:",
  cmpSkullsTime: "Skulls Split",
  cmpDebrisTime: "Debris Split",
  cmpFinished: "Finished",

  // Owner: adding and editing runs from the website (see editor.js)
  edOwnerSignIn: "Owner sign in",
  edSiteSettings: "Site settings",
  edSiteTitle: "Title",
  edSiteSubtitle: "Subtitle",
  edSiteNote: "Shown at the top of the site and in the browser tab.",
  edSiteNeedTitle: "The site needs a title.",
  edCommitName: "Rename the site (from the website)",
  welcomeTitle: "Welcome to your new stats site",
  welcomeText: "There are no runs yet. If this site is yours, set it up here: sign in, give it your name, then add your first run.",
  welcomeTextIn: "You're signed in. Give the site your name, then add your first run.",
  welcomeSetup: "Set up this site",
  welcomeName: "Name your site",
  welcomeFirstRun: "Add your first run",
  edSignedIn: repo => `Signed in to edit ${repo} ·`,
  edSignOut: "Sign out",
  edAddRun: "Add run",
  edEdit: "Edit",
  edEditRun: n => `Edit run ${n}`,
  edSignInTitle: "Sign in to edit this site",
  edSignInIntro: repo => `Only the owner of ${repo} can do this. You sign in once with a GitHub token that can save to that repository:`,
  edSignInSteps: repo => [
    `Open <a href="https://github.com/settings/personal-access-tokens/new" target="_blank" rel="noopener noreferrer">GitHub → Settings → Fine-grained tokens → Generate new token</a>.`,
    `Give it a name (e.g. "stats site") and an expiration.`,
    `Repository access: <b>Only select repositories</b> → <b>${esc(repo)}</b>.`,
    `Permissions: <b>Contents</b> → Read and write, and <b>Actions</b> → Read-only (to see when the site has updated).`,
    `Generate it, copy it, and paste it here.`,
  ],
  edToken: "Token",
  edTokenNote: "It's kept in this browser only and sent only to GitHub. Signing out removes it, and you can delete the token on GitHub at any time.",
  edTokenBad: "GitHub didn't accept this token. Check it's copied in full and hasn't expired.",
  edTokenNoWrite: repo => `This token can't save to ${repo}. Give it access to that repository with Contents: Read and write.`,
  edNoStorage: "This browser won't let the site remember the token (private window?).",
  edSignIn: "Sign in",
  edChecking: "Checking…",
  edCancel: "Cancel",
  edClose: "Close",
  edRunNumber: "Run number",
  edDate: "Date",
  edLog: "Hermes log",
  edLogPick: "Choose a log…",
  edLogReplace: "Replace the log…",
  edLogRead: (time, cat, deaths) => `${time} · ${cat} · ${deaths} death${deaths === 1 ? "" : "s"}`,
  edLogOnSite: "This run's log is already on the site.",
  edLogNone: "No log? Fill in what you know below.",
  edKeepLog: "Keep the full log in the repository (so future site updates can read it again)",
  edNoLogDetails: "Without a log",
  edDeaths: "Deaths",
  edDeathsNote: "Tick the deaths that were on purpose; they don't count as deaths. You can change how each one happened.",
  edDeathCause: k => `How death ${k} happened`,
  edStatsPick: "Read it from the world's stats file…",
  edStatsNone: "No elytra distance in that file (it's the world's stats/<uuid>.json).",
  edProof: "Proof",
  edVideoLink: "Link to the video",
  edShotLink: "Link to the screenshot",
  edShotOr: "or",
  edBadShotLink: "The screenshot link must start with https://",
  edPickRun: "Run",
  edNewRun: "New run",
  edShotPick: "Upload an image…",
  edShotReplace: "Replace the image…",
  edShotRemove: "Remove",
  edShotBad: "That isn't an image.",
  edDelete: "Delete run",
  edDeleteConfirm: n => `Delete run ${n}? Its log, screenshot and details are removed from the site.`,
  edSave: "Save",
  edSaving: "Saving…",
  edBadNumber: "The run number must be 1 or more.",
  edNumberTaken: n => `Run ${n} already exists. Open it and use Edit instead.`,
  edBadVideo: "The video must be a link starting with https://",
  edBadTime: what => `${what}: write it like 3:41:22 (or 3:41:22.629).`,
  edBadElytra: "Elytra distance must be a number of km.",
  edCommitAdd: n => `Add run ${n} (from the website)`,
  edCommitEdit: n => `Edit run ${n} (from the website)`,
  edCommitDelete: n => `Delete run ${n} (from the website)`,
  edSaved: "Saved. The site is updating…",
  edBuilding: "Saved. Building the site…",
  edSavedNoWatch: "Saved. The site updates in about a minute.",
  edLive: "Done: the site is updated.",
  edReload: "Reload to see it",
  edBuildFailed: "Saved, but the site's build failed.",
  edSeeBuild: "See progress",

  // Graph hover text
  hoverAdv: "Adv",
  hoverGold: "Gold",
  hoverTnt: "TNT",
  tridentMarker: (k, drowned) => `x${k} Trident (Drowned killed: ${drowned})`,
  skullMarker: (k, n, killed) => `${k}/${n} Wither Skulls (Killed: ${killed})`,
  nautilusMarker: (k, n) => `${k}/${n} Nautilus Shells`,
  godAppleMarker: "First God Apple",
  deathMarker: (k, n) => `Death ${k}/${n}`,
  // How a death happened (see deathCause in parse-log.js)
  deathCause: c => !c ? "Died" : c.startsWith("mob:") ? "Killed by " + titleCase(c.slice(4).replace(/_/g, " ")) :
    ({fire: "Burned to death", lava: "Died in lava", void: "Fell out of the world", impact: "Fall or explosion"})[c] || c,
  thunderMarker: "Thunder! (Very Very Frightening)",
  riptideMarker: (uses, dur) => `Riptide · ${uses} uses · ${dur}`,
  hoverRiptide: "Riptide",
  multiComplete: name => `${name} complete`,
  multiLast: crit => `Last: ${crit}`,
  debrisHover: (debris, tnt, rack) => `<b class="mono">${debris}</b> debris · <b class="mono">${tnt}</b> TNT` + (rack != null ? ` · <b class="mono">${rack}</b> netherrack` : ""),
  skullsHover: (ws, skulls) => `<b class="mono">${ws}</b> wither skeletons · <b class="mono">${skulls}</b> skulls`,
  rareComplete: "All biomes visited",
  skullOnChart: (k, killed) => `Skull ${k}/3 (Killed: ${killed})`,

  // Labels at the end of lines on the small graphs
  labelDebris: "Debris",
  labelNetherrack: "Netherrack",
  labelTnt: "TNT",
  labelWitherSkeletons: "Wither Skeletons",

  // Screen-reader names for the icon-only stat cards
  statDeaths: "Deaths",
  statElytra: "Elytra distance",
  statSkulls: "Skulls / wither skeletons killed",
  statSkullRate: "Wither skeletons killed per skull",
  statTntPerDebris: "TNT per debris",
  statShulkers: "Shulker Box Interactions",
  statCreepers: "Creeper Kills",
};
